### ISSUE TITLE
[Question] Vanilla JS usage ?

### ISSUE THREAD

**Issue by KaKi87** [chrisjpatty/flume#217]
Hello,

Is there any way to use this amazing looking library with vanilla JS, i.e. without the React framework ?

Thanks

**Comment by chrisjpatty** [comment]
Hi @KaKi87, React is required for rendering the node editor itself, but it's not required for executing your graphs. This page is might give you some direction on that: https://flume.dev/docs/using-without-react

**Comment by KaKi87** [comment]
Here's what I tried : https://jsfiddle.net/3vLy064m/

Here's the error I got :
```
react.js:185 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (react.js:185:13)
    at exports.useState (react.js:293:12)
    at ?editor_console=true:232:33
S @ react.js:185
exports.useState @ react.js:293
(anonymous) @ ?editor_console=true:232
```

Here's the content of the link :
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

Thanks
